apiServer:
  port: 8080
  publicHost: citesched-server.onrender.com
  publicPort: 443
  publicScheme: https

insightsServer:
  port: 8081
  publicHost: citesched-server.onrender.com
  publicPort: 443
  publicScheme: https

webServer:
  port: 8082
  publicHost: citesched-server.onrender.com
  publicPort: 443
  publicScheme: https

database:
  host: dpg-d7596dnfte5s7388qoa0-a.ohio-postgres.render.com
  port: 5432
  name: temp
  user: citesched_user
  requireSsl: true
  maxConnectionCount: 15

redis:
  enabled: false

maxRequestSize: 524288

sessionLogs:
  consoleEnabled: true